#!/bin/sh
# Explicit opt-in integration check. All endpoints/data/mounts are synthetic.
set -eu
umask 077
project=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
root=$(mktemp -d "${TMPDIR:-/tmp}/funnel-container-test.XXXXXX")
name=$(basename "$root" | tr '.' '-')
network=$name
volume=$name-vault
server=$name-sources
job=$name-job
cleanup() {
 docker rm -f "$job" "$server" >/dev/null 2>&1 || :
 docker volume rm "$volume" >/dev/null 2>&1 || :
 docker network rm "$network" >/dev/null 2>&1 || :
 rm -rf "$root"
}
stage=initialization
trap 'result=$?; if [ "$result" != 0 ]; then printf "FAIL container stage: %s\n" "$stage"; if [ -f "$root/publisher-log" ]; then grep -E "^(FAIL|funnel publisher:)" "$root/publisher-log" || :; fi; fi; cleanup' 0
trap 'exit 1' HUP INT TERM
# Prove the context allowlist excludes secrets/captures without using any secrets.
mkdir "$root/context"
cp "$project/go.mod" "$project/.dockerignore" "$root/context/"
cp -R "$project/cmd" "$project/internal" "$project/deploy" "$root/context/"
printf 'harmless-exclusion-sentinel' >"$root/context/dev.env"
printf 'harmless-exclusion-sentinel' >"$root/context/personal-capture.md"
printf 'harmless-exclusion-sentinel' >"$root/context/internal/brief/dev.env"
printf 'FROM scratch\nCOPY dev.env /sentinel\n' >"$root/context/check.Dockerfile"
if docker build -f "$root/context/check.Dockerfile" "$root/context" >"$root/context-check" 2>&1; then
 printf 'FAIL: context allowed excluded file\n';exit 1
fi
grep -q 'dev.env' "$root/context-check"
printf 'FROM scratch\nCOPY internal/brief/dev.env /sentinel\n' >"$root/context/check.Dockerfile"
if docker build -f "$root/context/check.Dockerfile" "$root/context" >"$root/context-check" 2>&1; then
 printf 'FAIL: context allowed nested env file\n';exit 1
fi
grep -q 'dev.env' "$root/context-check"
stage=image-build
docker build -f "$project/deploy/Dockerfile" -t funnel:local "$project" >"$root/build-log" 2>&1
arch=$(docker image inspect --format '{{.Architecture}}' funnel:local)
GOWORK=off GOTOOLCHAIN=local CGO_ENABLED=0 GOOS=linux GOARCH="$arch" \
 go build -o "$root/sources" "$project/deploy/testdata/sources.go"
chmod 755 "$root/sources"
docker network create "$network" >/dev/null
docker volume create "$volume" >/dev/null
docker run --rm --network none --read-only --user 0 --mount "type=volume,src=$volume,dst=/vault" \
 --entrypoint sh funnel:local -c 'chown 10001:10001 /vault; chmod 700 /vault'
docker run -d --name "$server" --network "$network" --network-alias sources --read-only \
 --mount "type=bind,src=$root/sources,dst=/sources,readonly" --entrypoint /sources funnel:local >/dev/null
mode() { docker exec "$server" sh -c "wget -q -O /dev/null 'http://localhost:8080/test/mode?state=$1'"; }
run_sync() {
 set +e
 docker run --rm --network "$network" --read-only --tmpfs /tmp:uid=10001,gid=10001,mode=700 \
 --mount "type=volume,src=$volume,dst=/vault" \
 -e DAWARICH_URL=http://sources:8080 -e DAWARICH_TOKEN=synthetic-token \
 -e PLEX_URL=http://sources:8080 -e PLEX_TOKEN=synthetic-token -e PLEX_USER_ID=7 \
 -e TZ=Pacific/Honolulu funnel:local sync --vault /vault --week "$1" >"$root/out" 2>"$root/log"
 code=$?
 set -e
 [ "$code" = "$2" ] || { printf 'FAIL container exit %s expected %s\n' "$code" "$2";exit 1; }
 if grep -q 'Synthetic\|synthetic-token' "$root/out" "$root/log";then printf 'FAIL private output\n';exit 1;fi
}
inspect() { docker run --rm --network none --read-only --mount "type=volume,src=$volume,dst=/vault" --entrypoint sh funnel:local -c "$1"; }
stage=fresh
sleep 1
run_sync 2024-W01 0
grep -qx 'Autogenerated/2024-W01 Funnel.md' "$root/out"
grep -q 'plex: fresh' "$root/log"
inspect 'test "$(id -u)" = 10001; test -r /usr/share/zoneinfo/Europe/Madrid; test -r /usr/local/bin/funnel-publish; grep -q "Synthetic movie" "/vault/Autogenerated/2024-W01 Funnel.md"'
stage=stale
mode fail
run_sync 2024-W01 2
inspect 'grep -q "Plex history · stale" "/vault/Autogenerated/2024-W01 Funnel.md"; grep -q "Synthetic movie" "/vault/Autogenerated/2024-W01 Funnel.md"'
stage=recovery
mode fresh
run_sync 2024-W01 0
stage=denied-write
before=$(inspect 'sha256sum "/vault/Autogenerated/2024-W01 Funnel.md"')
inspect 'chmod 500 /vault/Autogenerated'
run_sync 2024-W01 1
[ ! -s "$root/out" ]
[ "$before" = "$(inspect 'sha256sum "/vault/Autogenerated/2024-W01 Funnel.md"')" ]
inspect 'chmod 700 /vault/Autogenerated'
stage=runtime-DST
mode dst
run_sync 2024-W13 0
inspect 'grep -q "01:30–2024-03-31 04:30 +02:00" "/vault/Autogenerated/2024-W13 Funnel.md"'
mode fresh
# Refuse an unsafe target rather than creating a new brief.
stage=unsafe-target
inspect 'ln -s /tmp/outside "/vault/Autogenerated/2024-W02 Funnel.md"'
run_sync 2024-W02 1
[ ! -s "$root/out" ]
stage=cancellation
mode slow
docker run -d --name "$job" --network "$network" --read-only --mount "type=volume,src=$volume,dst=/vault" \
 -e DAWARICH_URL=http://sources:8080 -e DAWARICH_TOKEN=synthetic-token \
 -e PLEX_URL=http://sources:8080 -e PLEX_TOKEN=synthetic-token -e PLEX_USER_ID=7 \
 funnel:local sync --vault /vault --week 2024-W01 >/dev/null
sleep 1
docker stop -t 3 "$job" >/dev/null
[ "$(docker inspect --format '{{.State.ExitCode}}' "$job")" = 1 ]
stage=publisher
# Run the offline publisher suite on the actual Alpine shell/Git/binary too.
docker run --rm --network none --read-only --tmpfs /tmp:exec,uid=10001,gid=10001,mode=700 \
 --mount "type=bind,src=$project/deploy,dst=/suite/deploy,readonly" \
 -e FUNNEL_TEST_BIN=/usr/local/bin/funnel --entrypoint sh funnel:local /suite/deploy/publish_test.sh >"$root/publisher-log" 2>&1
printf 'PASS container: %s, non-root/read-only, 0/2/1, stale/recovery, cancellation, context exclusion, publisher\n' "$arch"
