#!/bin/sh
# Funnel publication is opt-in; this helper never uses the mounted user's vault.
set -u
umask 077
fail() { printf '%s\n' "funnel publisher: $1" >&2; exit 1; }
cr=$(printf '\r')
for key in FUNNEL_GIT_REMOTE FUNNEL_GIT_BRANCH FUNNEL_GIT_AUTHOR_NAME FUNNEL_GIT_AUTHOR_EMAIL TMPDIR; do
 # No eval: explicit variable dispatch keeps configuration as data.
 case "$key" in
  FUNNEL_GIT_REMOTE) value=${FUNNEL_GIT_REMOTE:-};;
  FUNNEL_GIT_BRANCH) value=${FUNNEL_GIT_BRANCH:-};;
  FUNNEL_GIT_AUTHOR_NAME) value=${FUNNEL_GIT_AUTHOR_NAME:-};;
  FUNNEL_GIT_AUTHOR_EMAIL) value=${FUNNEL_GIT_AUTHOR_EMAIL:-};;
  TMPDIR) value=${TMPDIR:-};;
 esac
 [ -n "$value" ] || fail 'required configuration missing'
 case "$value" in *"
"*|*"$cr"*) fail 'invalid configuration';; esac
done
case "$FUNNEL_GIT_REMOTE" in
 https://*@*|http://*|ssh://*:*@*|*\?*|*\#*|-*) fail 'unsafe remote; use external authentication and verified transport';;
esac
case "$FUNNEL_GIT_REMOTE" in
 https://*|ssh://*|/*|./*|../*|file:///*) ;;
 *@*:*) account=${FUNNEL_GIT_REMOTE%%@*};case "$account" in *:*|*/*) fail 'unsafe SSH account';;esac;;
 *) fail 'unsupported remote transport';;
esac
export GIT_TERMINAL_PROMPT=0
# Git output may include private remote URLs or file contents. Never print it.
work=$(mktemp -d "$TMPDIR/funnel-publish.XXXXXX" 2>/dev/null) || fail 'temporary storage unavailable'
child=
cleanup() {
 if [ -n "$child" ]; then kill "$child" 2>/dev/null || :; wait "$child" 2>/dev/null || :; fi
 rm -rf "$work"
}
trap cleanup 0
trap 'exit 1' HUP INT TERM
git_call() {
 git -c core.hooksPath=/dev/null -c credential.interactive=false \
  -c http.sslVerify=true -c http.lowSpeedLimit=1 -c http.lowSpeedTime=30 "$@" >"$work/git.log" 2>&1 &
 child=$!; wait "$child"; git_result=$?; child=; return "$git_result"
}
git_call check-ref-format --branch "$FUNNEL_GIT_BRANCH" || fail 'invalid branch'
git_call clone --quiet --single-branch --branch "$FUNNEL_GIT_BRANCH" -- "$FUNNEL_GIT_REMOTE" "$work/checkout" || fail 'checkout failed'
cd "$work/checkout" || fail 'checkout unavailable'
[ "$(git symbolic-ref --short HEAD 2>/dev/null)" = "$FUNNEL_GIT_BRANCH" ] || fail 'branch mismatch'
[ -z "$(git status --porcelain --untracked-files=all 2>/dev/null)" ] || fail 'checkout not clean'
"${FUNNEL_BIN:-funnel}" sync --vault "$work/checkout" >"$work/reported" 2>"$work/funnel.log" &
child=$!; wait "$child"; result=$?; child=
# The trusted CLI's stderr contract is redacted source/week status, not cue text.
cat "$work/funnel.log" >&2
case "$result" in 0|2) ;; *) fail 'sync fatal; nothing published';; esac
valid_path() { printf '%s\n' "$1" | LC_ALL=C grep -Eq '^Autogenerated/[0-9]{4}-W(0[1-9]|[1-4][0-9]|5[0-3]) Funnel\.md$'; }
: >"$work/actual"
git -c core.quotePath=true status --porcelain=v1 --untracked-files=all >"$work/status" 2>"$work/git.log" || fail 'change inventory failed'
while IFS= read -r line || [ -n "$line" ]; do
 kind=$(printf '%.3s' "$line")
 case "$kind" in ' M '|'?? ') ;; *) fail 'unexpected staged/deleted/renamed change';; esac
 path=${line#???}
 # Git quotes names containing spaces; this namespace has no escape sequences.
 case "$path" in \"*\") path=${path#\"}; path=${path%\"};; esac
 valid_path "$path" || fail 'unowned change'
 printf '%s\n' "$path" >>"$work/actual"
done <"$work/status"
while IFS= read -r path || [ -n "$path" ]; do
 valid_path "$path" || fail 'unsafe reported path'
 [ -f "$path" ] && [ ! -L "$path" ] && [ ! -L Autogenerated ] || fail 'unsafe generated file'
 week=${path#Autogenerated/};week=${week% Funnel.md}
 printf '%s\n' '---' 'generator: funnel' 'funnel_schema: 1' "funnel_week: $week" '---' >"$work/header"
 head -n 5 "$path" >"$work/found-header"
 cmp -s "$work/header" "$work/found-header" || fail 'unsupported ownership/schema/week'
 [ "$(grep -c '^<!-- funnel:state ' "$path")" = 1 ] || fail 'missing/ambiguous state'
 [ "$(grep -c '^<!-- funnel:begin ' "$path")" = 14 ] || fail 'invalid cue format'
 [ "$(grep -c '^<!-- funnel:end ' "$path")" = 14 ] || fail 'invalid cue format'
done <"$work/reported"
LC_ALL=C sort "$work/reported" >"$work/reported-sorted"
LC_ALL=C sort -u "$work/reported" >"$work/reported-unique"
cmp -s "$work/reported-sorted" "$work/reported-unique" || fail 'duplicate reported path'
LC_ALL=C sort "$work/actual" >"$work/actual-sorted"
cmp -s "$work/reported-sorted" "$work/actual-sorted" || fail 'reported paths differ from complete Git change set'
if [ ! -s "$work/actual" ]; then printf 'funnel publisher: unchanged\n' >&2; exit "$result"; fi
while IFS= read -r path; do git_call add -- "$path" || fail 'exact-path staging failed'; done <"$work/actual"
export GIT_AUTHOR_NAME="$FUNNEL_GIT_AUTHOR_NAME" GIT_AUTHOR_EMAIL="$FUNNEL_GIT_AUTHOR_EMAIL"
export GIT_COMMITTER_NAME="$FUNNEL_GIT_AUTHOR_NAME" GIT_COMMITTER_EMAIL="$FUNNEL_GIT_AUTHOR_EMAIL"
git_call -c commit.gpgSign=false commit --quiet -m 'Refresh generated Funnel briefs' || fail 'commit failed'
expected=$(git rev-parse HEAD 2>/dev/null) || fail 'commit identity unavailable'
if git_call push --quiet origin "HEAD:refs/heads/$FUNNEL_GIT_BRANCH"; then
 printf 'funnel publisher: published\n' >&2
 exit "$result"
fi
# A failed response can mean an accepted push. Fetch remote state, never rebase,
# merge, force-push or retry this checkout. An advanced branch may include ours.
if ! git_call fetch --quiet origin "refs/heads/$FUNNEL_GIT_BRANCH"; then
 fail 'publication outcome unknown; remote verification failed'
fi
if git_call merge-base --is-ancestor "$expected" FETCH_HEAD; then
 printf 'funnel publisher: publication confirmed after lost response\n' >&2
 exit "$result"
fi
fail 'expected commit absent from remote branch; retry only from a fresh checkout'
