#!/bin/sh
# Offline: synthetic Markdown and disposable local repositories only.
set -eu
umask 077
root=$(mktemp -d "${TMPDIR:-/tmp}/funnel-publisher-test.XXXXXX")
trap 'rm -rf "$root"' 0
trap 'exit 1' HUP INT TERM
project=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
export GIT_CONFIG_NOSYSTEM=1 GIT_CONFIG_GLOBAL=/dev/null GIT_TERMINAL_PROMPT=0
export GIT_AUTHOR_NAME='Synthetic Test' GIT_AUTHOR_EMAIL='test@example.invalid'
export GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME" GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL"
if [ -n "${FUNNEL_TEST_BIN:-}" ]; then
 cp "$FUNNEL_TEST_BIN" "$root/funnel"
else
 GOWORK=off GOTOOLCHAIN=local go build -o "$root/funnel" "$project/cmd/funnel"
fi
mkdir "$root/fixture"
set +e
DAWARICH_URL=http://127.0.0.1:1 DAWARICH_TOKEN=synthetic-token \
PLEX_URL=http://127.0.0.1:1 PLEX_TOKEN=synthetic-token PLEX_USER_ID=7 \
 "$root/funnel" sync --vault "$root/fixture" --week 2024-W01 >"$root/fixture-paths" 2>"$root/fixture-log"
code=$?
set -e
[ "$code" = 2 ] || { printf 'FAIL synthetic fixture exit %s\n' "$code"; grep '^funnel:' "$root/fixture-log" || :;exit 1; }
export FIXTURE="$root/fixture/Autogenerated/2024-W01 Funnel.md"
cat >"$root/stub" <<'SH'
#!/bin/sh
set -eu
vault=$3
if [ "$SCENARIO" = noop ]; then exit 0; fi
if [ "$SCENARIO" = cancel ]; then exec sleep 30; fi
mkdir -p "$vault/Autogenerated"
cp "$FIXTURE" "$vault/Autogenerated/2024-W01 Funnel.md"
case "$SCENARIO" in
 unrelated) printf 'changed' > "$vault/personal.md" ;;
 invalid) printf 'personal' > "$vault/Autogenerated/2024-W01 Funnel.md" ;;
 fatal) exit 1 ;;
 unsafe) printf '../personal.md\n'; exit 0 ;;
esac
printf 'Autogenerated/2024-W01 Funnel.md\n'
if [ "$SCENARIO" = degraded ]; then exit 2; fi
SH
chmod 700 "$root/stub"
export FUNNEL_BIN="$root/stub" FUNNEL_GIT_BRANCH=main
export FUNNEL_GIT_AUTHOR_NAME='Synthetic Automation' FUNNEL_GIT_AUTHOR_EMAIL='automation@example.invalid'
mkdir "$root/temp"
export TMPDIR="$root/temp"
for SCENARIO in fresh degraded noop fatal unrelated invalid unsafe; do
 export SCENARIO
 remote="$root/$SCENARIO.git";seed="$root/$SCENARIO-seed"
 git init --bare -q "$remote"
 git init -q -b main "$seed"
 printf 'personal preserved\n' > "$seed/personal.md"
 git -C "$seed" add personal.md
 git -C "$seed" commit -qm 'Synthetic baseline'
 git -C "$seed" push -q "$remote" HEAD:main
 before=$(git --git-dir="$remote" rev-parse main)
 export FUNNEL_GIT_REMOTE="$remote"
 set +e
 sh "$project/deploy/publish.sh" >"$root/out" 2>"$root/log"
 code=$?
 set -e
 expected=1
 case "$SCENARIO" in fresh|noop) expected=0;; degraded) expected=2;; esac
 if [ "$code" != "$expected" ]; then printf 'FAIL %s: exit %s expected %s\n' "$SCENARIO" "$code" "$expected"; grep '^funnel publisher:' "$root/log" || :; exit 1; fi
 after=$(git --git-dir="$remote" rev-parse main)
 case "$SCENARIO" in
  fresh|degraded) [ "$before" != "$after" ]; git --git-dir="$remote" diff --name-only "$before" "$after" >"$root/actual"; printf 'Autogenerated/2024-W01 Funnel.md\n' >"$root/wanted";cmp "$root/actual" "$root/wanted";;
  *) [ "$before" = "$after" ];;
 esac
 [ "$(git --git-dir="$remote" show main:personal.md)" = 'personal preserved' ]
 [ -z "$(ls -A "$TMPDIR")" ]
 if grep -q 'synthetic-token\|Synthetic outing\|personal preserved' "$root/out" "$root/log"; then exit 1; fi
 printf 'PASS publisher %s\n' "$SCENARIO"
done

# Isolated Git shim: real local pushes with controlled lost responses/rivals.
export REAL_GIT=$(command -v git)
mkdir "$root/shim"
cat >"$root/shim/git" <<'SH'
#!/bin/sh
set -eu
verb=
for arg do
 case "$arg" in clone|push|fetch) verb=$arg;break;; esac
done
if [ "$SCENARIO" = auth ] && [ "$verb" = clone ]; then exit 1; fi
if [ "$SCENARIO" = unknown ] && [ "$verb" = fetch ]; then exit 1; fi
rival() {
 "$REAL_GIT" clone -q --branch main "$FUNNEL_GIT_REMOTE" "$RIVAL" > /dev/null 2>&1
 printf 'competing personal update\n' > "$RIVAL/personal.md"
 "$REAL_GIT" -C "$RIVAL" add personal.md
 "$REAL_GIT" -C "$RIVAL" commit -qm 'Synthetic competing writer'
 "$REAL_GIT" -C "$RIVAL" push -q origin main
}
if [ "$verb" = push ]; then
 case "$SCENARIO" in
  reject) rival; exec "$REAL_GIT" "$@";;
  lost|unknown) "$REAL_GIT" "$@";exit 1;;
  advanced) "$REAL_GIT" "$@";rival;exit 1;;
 esac
fi
exec "$REAL_GIT" "$@"
SH
chmod 700 "$root/shim/git"
export PATH="$root/shim:$PATH"
for SCENARIO in reject lost advanced unknown auth cancel; do
 export SCENARIO
 remote="$root/$SCENARIO.git";seed="$root/$SCENARIO-seed"
 "$REAL_GIT" init --bare -q "$remote"
 "$REAL_GIT" init -q -b main "$seed"
 printf 'personal preserved\n' > "$seed/personal.md"
 "$REAL_GIT" -C "$seed" add personal.md
 "$REAL_GIT" -C "$seed" commit -qm 'Synthetic baseline'
 "$REAL_GIT" -C "$seed" push -q "$remote" HEAD:main
 export FUNNEL_GIT_REMOTE="$remote" RIVAL="$root/$SCENARIO-rival"
 before=$("$REAL_GIT" --git-dir="$remote" rev-parse main)
 set +e
 if [ "$SCENARIO" = cancel ]; then
  sh "$project/deploy/publish.sh" >"$root/out" 2>"$root/log" & pid=$!
  sleep 1;kill -TERM "$pid";wait "$pid";code=$?
 else
  sh "$project/deploy/publish.sh" >"$root/out" 2>"$root/log";code=$?
 fi
 set -e
 expected=1;case "$SCENARIO" in lost|advanced) expected=0;;esac
 [ "$code" = "$expected" ] || { printf 'FAIL failure scenario %s\n' "$SCENARIO";exit 1; }
 [ -z "$(ls -A "$TMPDIR")" ]
 case "$SCENARIO" in
  unknown) grep -q 'outcome unknown' "$root/log";[ "$("$REAL_GIT" --git-dir="$remote" rev-parse main)" != "$before" ];;
  reject)
   [ "$("$REAL_GIT" --git-dir="$remote" show main:personal.md)" = 'competing personal update' ]
   SCENARIO=retry;export SCENARIO
   sh "$project/deploy/publish.sh" >"$root/out" 2>"$root/log"
   [ "$("$REAL_GIT" --git-dir="$remote" show main:personal.md)" = 'competing personal update' ];;
  lost|advanced) grep -q 'publication confirmed' "$root/log";;
  auth|cancel) [ "$("$REAL_GIT" --git-dir="$remote" rev-parse main)" = "$before" ];;
 esac
 printf 'PASS publisher failure %s\n' "$SCENARIO"
done
