package main

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func fakeSources(t *testing.T, failed *bool) *httptest.Server {
	t.Helper()
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if failed != nil && *failed {
			http.Error(w, "secret-sentinel", 500)
			return
		}
		switch r.URL.Path {
		case "/identity":
			fmt.Fprint(w, `{"MediaContainer":{"machineIdentifier":"synthetic-server"}}`)
		case "/accounts":
			fmt.Fprint(w, `{"MediaContainer":{"Account":[{"id":7,"name":"sample"}]}}`)
		case "/status/sessions/history/all":
			fmt.Fprint(w, `{"MediaContainer":{"size":0,"offset":0,"totalSize":0}}`)
		case "/api/v1/users/me":
			fmt.Fprint(w, `{"user":{"email":"synthetic@example.invalid"}}`)
		case "/api/v1/visits":
			w.Header().Set("X-Current-Page", "1")
			w.Header().Set("X-Total-Pages", "0")
			w.Header().Set("X-Total-Count", "0")
			fmt.Fprint(w, `[]`)
		default:
			t.Errorf("unexpected request %s", r.URL.Path)
			http.NotFound(w, r)
		}
	}))
	t.Cleanup(server.Close)
	return server
}
func fakeEnv(base string) func(string) string {
	return func(key string) string {
		switch key {
		case "PLEX_URL", "DAWARICH_URL":
			return base
		case "PLEX_TOKEN", "DAWARICH_TOKEN":
			return "secret-sentinel"
		case "PLEX_USER_ID":
			return "7"
		}
		return ""
	}
}
func TestCrossSourceCredentialEchoRefusesWrites(t *testing.T) {
	base := fakeSources(t, nil)
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path == "/status/sessions/history/all" {
			fmt.Fprint(w, `{"MediaContainer":{"size":1,"offset":0,"totalSize":1,"Metadata":[{"accountID":7,"type":"movie","historyKey":"/status/sessions/history/1","viewedAt":1704196800,"title":"other-secret-token"}]}}`)
			return
		}
		base.Config.Handler.ServeHTTP(w, r)
	}))
	defer server.Close()
	env := func(key string) string {
		if key == "DAWARICH_TOKEN" {
			return "other-secret-token"
		}
		return fakeEnv(server.URL)(key)
	}
	vault := t.TempDir()
	var out, stderr bytes.Buffer
	code := run(context.Background(), []string{"sync", "--vault", vault, "--week", "2024-W01"}, env, time.Date(2024, 1, 8, 12, 0, 0, 0, time.UTC), nil, &out, &stderr)
	if code != 1 || strings.Contains(out.String()+stderr.String(), "other-secret-token") {
		t.Fatal("credential echo not refused")
	}
	if _, err := os.Stat(filepath.Join(vault, "Autogenerated")); !os.IsNotExist(err) {
		t.Fatal("secret-bearing output written")
	}
}

func TestCrossModuleDelayedRewatchStaleAndNewProcess(t *testing.T) {
	now := time.Date(2024, 1, 8, 12, 0, 0, 0, time.UTC)
	mode := 0
	machine := "synthetic-server"
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if mode == 2 || (mode == 1 && strings.HasPrefix(r.URL.Path, "/status/")) {
			http.Error(w, "secret-sentinel", 500)
			return
		}
		switch r.URL.Path {
		case "/identity":
			json.NewEncoder(w).Encode(map[string]any{"MediaContainer": map[string]any{"machineIdentifier": machine}})
		case "/accounts":
			fmt.Fprint(w, `{"MediaContainer":{"Account":[{"id":7,"name":"sample"}]}}`)
		case "/api/v1/users/me":
			fmt.Fprint(w, `{"user":{"email":"synthetic@example.invalid"}}`)
		case "/status/sessions/history/all":
			rows := []map[string]any{}
			if mode != 3 {
				for _, id := range []int{1, 1, 2} {
					rows = append(rows, map[string]any{"historyKey": fmt.Sprintf("/status/sessions/history/%d", id), "accountID": 7, "viewedAt": 1704196800 + id, "type": "movie", "title": "Synthetic [[title]]", "ratingKey": "9"})
				}
				if mode == 4 {
					rows = append(rows, map[string]any{"historyKey": "/status/sessions/history/4", "accountID": 7, "viewedAt": 1704196804, "type": "movie", "title": "Delayed entry"})
				}
			}
			json.NewEncoder(w).Encode(map[string]any{"MediaContainer": map[string]any{"size": len(rows), "offset": 0, "totalSize": len(rows), "Metadata": rows}})
		case "/api/v1/visits":
			w.Header().Set("X-Current-Page", "1")
			w.Header().Set("X-Total-Pages", "1")
			w.Header().Set("X-Total-Count", "1")
			fmt.Fprint(w, `[{"id":1,"user_id":7,"started_at":"2024-01-02T12:00:00Z","ended_at":null,"name":"Synthetic outing","status":"suggested","place":{"latitude":40,"longitude":-3}}]`)
		}
	}))
	defer server.Close()
	vault := t.TempDir()
	invoke := func(expected int) []byte {
		t.Helper()
		var out, stderr bytes.Buffer
		code := run(context.Background(), []string{"sync", "--vault", vault, "--week", "2024-W01"}, fakeEnv(server.URL), now, nil, &out, &stderr)
		if code != expected || strings.Contains(out.String()+stderr.String(), "secret-sentinel") {
			t.Fatalf("code %d diagnostics %s", code, &stderr)
		}
		raw, err := os.ReadFile(filepath.Join(vault, "Autogenerated/2024-W01 Funnel.md"))
		if err != nil {
			t.Fatal(err)
		}
		now = now.Add(time.Minute)
		return raw
	}
	first := invoke(0)
	if strings.Count(string(first), "Synthetic &#91;") != 2 || strings.Contains(string(first), "[[title]]") {
		t.Fatal("duplicate/rewatch or injection")
	}
	// Copy only the Markdown to a new checkout; no in-memory provider state survives.
	vault = t.TempDir()
	os.Mkdir(filepath.Join(vault, "Autogenerated"), 0700)
	os.WriteFile(filepath.Join(vault, "Autogenerated/2024-W01 Funnel.md"), first, 0600)
	mode = 1
	stale := invoke(2)
	if strings.Count(string(stale), "Synthetic &#91;") != 2 || !strings.Contains(string(stale), "Plex history · stale") {
		t.Fatal("stale lost history")
	}
	mode = 2
	invoke(2)
	mode = 3
	empty := invoke(0)
	if strings.Contains(string(empty), "Synthetic &#91;") {
		t.Fatal("empty failed to replace")
	}
	mode = 4
	late := invoke(0)
	if !strings.Contains(string(late), "Delayed entry") {
		t.Fatal("delayed data missing")
	}
	machine = "changed-server"
	refused := invoke(1)
	if !bytes.Equal(late, refused) {
		t.Fatal("identity mismatch wrote output")
	}
}

func TestWritesRollingStaleRecoveryAndFatal(t *testing.T) {
	failed := false
	server := fakeSources(t, &failed)
	vault := t.TempDir()
	now := time.Date(2024, 1, 8, 12, 0, 0, 0, time.UTC)
	for _, expected := range []int{0, 2, 0} {
		failed = expected == 2
		var out, stderr bytes.Buffer
		code := run(context.Background(), []string{"sync", "--vault", vault}, fakeEnv(server.URL), now, nil, &out, &stderr)
		if code != expected {
			t.Fatalf("code %d: %s", code, &stderr)
		}
		if expected == 2 {
			for _, detail := range []string{
				"week=2024-W01 source=plex operation=identity category=http attempts=4 http_status=500",
				"week=2024-W01 source=dawarich operation=users_me category=http attempts=4 http_status=500",
			} {
				if !strings.Contains(stderr.String(), detail) {
					t.Fatalf("missing sanitized failure detail %q: %s", detail, &stderr)
				}
			}
			if strings.Contains(stderr.String(), "secret-sentinel") {
				t.Fatal("failure diagnostics leaked a credential")
			}
		}
		for _, line := range strings.Split(strings.TrimSpace(out.String()), "\n") {
			if !strings.HasPrefix(line, "Autogenerated/") || !strings.HasSuffix(line, " Funnel.md") {
				t.Fatal("non-path stdout")
			}
		}
		raw, err := os.ReadFile(filepath.Join(vault, "Autogenerated/2024-W01 Funnel.md"))
		if err != nil {
			t.Fatal(err)
		}
		if expected == 2 && !strings.Contains(string(raw), "stale") {
			t.Fatal("not stale")
		}
		now = now.Add(time.Minute)
	}
	// A fatal collision in any selected week prevents every sibling update.
	first := filepath.Join(vault, "Autogenerated/2024-W01 Funnel.md")
	before, _ := os.ReadFile(first)
	os.WriteFile(filepath.Join(vault, "Autogenerated/2024-W02 Funnel.md"), []byte("personal collision"), 0600)
	var out, stderr bytes.Buffer
	if run(context.Background(), []string{"sync", "--vault", vault}, fakeEnv(server.URL), now, nil, &out, &stderr) != 1 {
		t.Fatal("collision accepted")
	}
	after, _ := os.ReadFile(first)
	if !bytes.Equal(before, after) {
		t.Fatal("sibling changed on fatal")
	}
}

func TestDryRunSourcesAndHelp(t *testing.T) {
	failed := false
	server := fakeSources(t, &failed)
	vault := t.TempDir()
	now := time.Date(2024, 1, 8, 12, 0, 0, 0, time.UTC)
	for _, want := range []int{0, 2} {
		failed = want == 2
		var out, errout bytes.Buffer
		code := run(context.Background(), []string{"sync", "--vault", vault, "--week", "2024-W01", "--dry-run"}, fakeEnv(server.URL), now, nil, &out, &errout)
		if code != want || strings.Contains(out.String()+errout.String(), "secret-sentinel") {
			t.Fatalf("code %d: %s / %s", code, &out, &errout)
		}
	}
	var out, errout bytes.Buffer
	code := run(context.Background(), []string{"--help"}, func(string) string { t.Fatal("help accessed env"); return "" }, now, nil, &out, &errout)
	if code != 0 || !strings.Contains(out.String(), "--vault") {
		t.Fatal("help failed")
	}
}
