// Package brief groups factual cues and owns only Funnel weekly Markdown.
package brief

import (
	"errors"
	"fmt"
	"math"
	"net/url"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"
	"unicode"
)

var Madrid = mustMadrid()

func mustMadrid() *time.Location {
	loc, err := time.LoadLocation("Europe/Madrid")
	if err != nil {
		panic("Europe/Madrid timezone data required")
	}
	return loc
}

var weekPattern = regexp.MustCompile(`^([0-9]{4})-W([0-9]{2})$`)
var Sources = []string{"dawarich", "plex"}

type Week struct {
	Name  string
	Start time.Time
}

func ParseWeek(name string) (Week, error) {
	m := weekPattern.FindStringSubmatch(name)
	if m == nil {
		return Week{}, errors.New("invalid week")
	}
	y, _ := strconv.Atoi(m[1])
	n, _ := strconv.Atoi(m[2])
	if y < 2 || y > 9998 {
		return Week{}, errors.New("invalid week")
	}
	jan := time.Date(y, 1, 4, 0, 0, 0, 0, time.UTC)
	monday := jan.AddDate(0, 0, -(int(jan.Weekday())+6)%7).AddDate(0, 0, 7*(n-1))
	iy, iw := monday.ISOWeek()
	if iy != y || iw != n {
		return Week{}, errors.New("invalid week")
	}
	return Week{name, monday}, nil
}
func (w Week) Path() string { return "Autogenerated/" + w.Name + " Funnel.md" }

type Cue struct {
	Source, ID              string
	Start                   time.Time
	End                     *time.Time
	Zone                    *time.Location
	Text, Uncertainty, Link string
}

func Escape(text string) string {
	text = strings.Join(strings.Fields(text), " ")
	var b strings.Builder
	for _, r := range text {
		if r < 128 && (unicode.IsPunct(r) || unicode.IsSymbol(r)) {
			fmt.Fprintf(&b, "&#%d;", r)
		} else if !unicode.IsControl(r) {
			b.WriteRune(r)
		}
	}
	return b.String()
}
func safeMap(link string) bool {
	u, e := url.Parse(link)
	if e != nil || u.Scheme != "https" || u.Host != "www.google.com" || u.Path != "/maps/search/" || u.User != nil || u.Fragment != "" {
		return false
	}
	q := u.Query()
	if len(q) != 2 || len(q["api"]) != 1 || q.Get("api") != "1" || len(q["query"]) != 1 {
		return false
	}
	pair := strings.Split(q.Get("query"), ",")
	if len(pair) != 2 {
		return false
	}
	lat, e1 := strconv.ParseFloat(pair[0], 64)
	lon, e2 := strconv.ParseFloat(pair[1], 64)
	return e1 == nil && e2 == nil && !math.IsNaN(lat) && !math.IsNaN(lon) && lat >= -90 && lat <= 90 && lon >= -180 && lon <= 180
}
func cueBlocks(w Week, now time.Time, cues []Cue) (map[string]string, error) {
	blocks := map[string]string{}
	seen := map[string]Cue{}
	sort.SliceStable(cues, func(i, j int) bool {
		if cues[i].Start.Equal(cues[j].Start) {
			return cues[i].Source+"/"+cues[i].ID < cues[j].Source+"/"+cues[j].ID
		}
		return cues[i].Start.Before(cues[j].Start)
	})
	for _, c := range cues {
		if (c.Source != "plex" && c.Source != "dawarich") || c.ID == "" || c.Start.IsZero() || (c.End != nil && !c.End.After(c.Start)) {
			return nil, errors.New("invalid cue")
		}
		key := c.Source + "/" + c.ID
		if _, ok := seen[key]; ok {
			continue
		}
		seen[key] = c
		if c.Start.After(now) {
			continue
		}
		zone := c.Zone
		if zone == nil {
			zone = Madrid
		}
		local := c.Start.In(zone)
		date := local.Format("2006-01-02")
		if date < w.Start.Format("2006-01-02") || date >= w.Start.AddDate(0, 0, 7).Format("2006-01-02") {
			continue
		}
		label := local.Format("15:04")
		if c.Zone != nil {
			label += " " + local.Format("-07:00") + " (" + Escape(zone.String()) + ")"
		}
		if c.End != nil {
			end := c.End.In(zone)
			_, offset := local.Zone()
			_, endOffset := end.Zone()
			if local.Format("2006-01-02") != end.Format("2006-01-02") || offset != endOffset {
				label += "–" + end.Format("2006-01-02 15:04 -07:00")
			} else {
				label += "–" + end.Format("15:04")
			}
		} else if c.Source == "dawarich" {
			label += "–end unknown"
		}
		emoji := "📍"
		if c.Source == "plex" {
			emoji = "🍿"
		}
		line := "- " + emoji + " " + label + " · " + Escape(c.Text)
		if c.Uncertainty != "" {
			line += " · " + Escape(c.Uncertainty)
		}
		if c.Link != "" {
			if !safeMap(c.Link) {
				return nil, errors.New("unsafe link")
			}
			line += " · [Map](" + c.Link + ")"
		}
		// ponytail: concatenation is bounded to 10,000 source rows; use per-day builders if large weeks become slow.
		blocks[date+"/"+c.Source] += line + "\n"
	}
	return blocks, nil
}
