package brief

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"
	"time"
)

func TestVaultPreflightAtomicWriteAndIsolation(t *testing.T) {
	root := t.TempDir()
	w, _ := ParseWeek("2024-W01")
	now := time.Date(2024, 1, 8, 12, 0, 0, 0, time.UTC)
	personal := filepath.Join(root, "personal.md")
	os.WriteFile(personal, []byte("do not touch"), 0600)
	v, err := OpenVault(root, []Week{w})
	if err != nil {
		t.Fatal(err)
	}
	defer v.Close()
	doc, err := Update(w, now, v.Previous[w.Name], syntheticRefresh(nil))
	if err != nil {
		t.Fatal(err)
	}
	if _, err := v.Write(map[string]*Document{w.Name: doc}, true); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(root, "Autogenerated")); !os.IsNotExist(err) {
		t.Fatal("dry-run wrote")
	}
	changed, err := v.Write(map[string]*Document{w.Name: doc}, false)
	if err != nil || len(changed) != 1 {
		t.Fatal("write failed", err)
	}
	raw, err := os.ReadFile(filepath.Join(root, w.Path()))
	if err != nil || !bytes.Equal(raw, doc.Bytes()) {
		t.Fatal("wrong bytes")
	}
	unchanged, err := v.Write(map[string]*Document{w.Name: doc}, false)
	if err != nil || len(unchanged) != 0 {
		t.Fatal("identical file rewritten", err)
	}
	b, _ := os.ReadFile(personal)
	if string(b) != "do not touch" {
		t.Fatal("personal modified")
	}
	entries, _ := os.ReadDir(filepath.Join(root, "Autogenerated"))
	if len(entries) != 1 {
		t.Fatal("temporary file leaked")
	}
}
func TestReplacementFailureAndConcurrentChanges(t *testing.T) {
	root := t.TempDir()
	os.Mkdir(filepath.Join(root, "target"), 0700)
	r, err := os.OpenRoot(root)
	if err != nil {
		t.Fatal(err)
	}
	defer r.Close()
	if err := replace(r, "target", []byte("new"), 0600); err == nil {
		t.Fatal("rename into directory succeeded")
	}
	entries, _ := os.ReadDir(root)
	if len(entries) != 1 || entries[0].Name() != "target" {
		t.Fatal("failed replacement leaked temporary file")
	}
	w, _ := ParseWeek("2024-W01")
	v, err := OpenVault(root, []Week{w})
	if err != nil {
		t.Fatal(err)
	}
	defer v.Close()
	os.Mkdir(filepath.Join(root, "Autogenerated"), 0700)
	path := filepath.Join(root, w.Path())
	os.WriteFile(path, []byte("concurrent personal edit"), 0600)
	doc, _ := Update(w, time.Date(2024, 1, 8, 0, 0, 0, 0, time.UTC), nil, syntheticRefresh(nil))
	if _, err := v.Write(map[string]*Document{w.Name: doc}, false); err == nil {
		t.Fatal("concurrent change overwritten")
	}
	raw, _ := os.ReadFile(path)
	if string(raw) != "concurrent personal edit" {
		t.Fatal("concurrent content lost")
	}
}

func TestVaultRefusesEveryUnsafeTargetBeforeWrites(t *testing.T) {
	for _, mode := range []string{"collision", "symlink", "directory", "parent-link", "malformed"} {
		t.Run(mode, func(t *testing.T) {
			root := t.TempDir()
			outside := t.TempDir()
			w, _ := ParseWeek("2024-W01")
			other, _ := ParseWeek("2023-W52")
			dir := filepath.Join(root, "Autogenerated")
			if mode == "parent-link" {
				os.Symlink(outside, dir)
			} else {
				os.Mkdir(dir, 0700)
			}
			target := filepath.Join(root, w.Path())
			switch mode {
			case "collision":
				os.WriteFile(target, []byte("personal"), 0600)
			case "symlink":
				os.WriteFile(filepath.Join(outside, "secret"), []byte("private"), 0600)
				os.Symlink(filepath.Join(outside, "secret"), target)
			case "directory":
				os.Mkdir(target, 0700)
			case "malformed":
				os.WriteFile(target, []byte("---\ngenerator: funnel\n---\n"), 0600)
			}
			if v, err := OpenVault(root, []Week{other, w}); err == nil {
				v.Close()
				t.Fatal("accepted unsafe target")
			}
			if _, err := os.Stat(filepath.Join(root, other.Path())); !os.IsNotExist(err) {
				t.Fatal("sibling was written")
			}
		})
	}
}
