package brief

import (
	"bytes"
	"crypto/rand"
	"errors"
	"io"
	"os"
	"strings"
)

// os.Root confines every filesystem operation, including temporary renames.
// https://pkg.go.dev/os#Root. External writers must not overlap a sync.
type Vault struct {
	root     *os.Root
	weeks    []Week
	Previous map[string]*Document
	saved    map[string][]byte
}

func OpenVault(path string, weeks []Week) (*Vault, error) {
	st, err := os.Lstat(path)
	if err != nil || !st.IsDir() || st.Mode()&os.ModeSymlink != 0 {
		return nil, errors.New("unsafe vault")
	}
	root, err := os.OpenRoot(path)
	if err != nil {
		return nil, errors.New("vault access")
	}
	v := &Vault{root: root, weeks: weeks, Previous: map[string]*Document{}, saved: map[string][]byte{}}
	fail := func(err error) (*Vault, error) { root.Close(); return nil, err }
	if err := v.checkDirectory(); err != nil {
		return fail(err)
	}
	seen := map[string]bool{}
	for _, w := range weeks {
		canonical, err := ParseWeek(w.Name)
		if err != nil || canonical.Start != w.Start || seen[w.Name] {
			return fail(errors.New("invalid targets"))
		}
		seen[w.Name] = true
		data, _, err := v.read(w.Path())
		if err != nil {
			return fail(err)
		}
		v.saved[w.Name] = data
		if data != nil {
			doc, err := ParseDocument(w, data)
			if err != nil {
				return fail(err)
			}
			v.Previous[w.Name] = doc
		}
	}
	return v, nil
}
func (v *Vault) Close() error { return v.root.Close() }
func (v *Vault) checkDirectory() error {
	st, err := v.root.Lstat("Autogenerated")
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil || !st.IsDir() || st.Mode()&os.ModeSymlink != 0 {
		return errors.New("unsafe generated directory")
	}
	return nil
}
func (v *Vault) read(path string) ([]byte, os.FileMode, error) {
	st, err := v.root.Lstat(path)
	if os.IsNotExist(err) {
		return nil, 0600, nil
	}
	if err != nil || !st.Mode().IsRegular() {
		return nil, 0, errors.New("unsafe output target")
	}
	if st.Size() > 4<<20 {
		return nil, 0, errors.New("document limit")
	}
	f, err := v.root.Open(path)
	if err != nil {
		return nil, 0, errors.New("output access")
	}
	defer f.Close()
	b, err := io.ReadAll(io.LimitReader(f, 4<<20+1))
	if err != nil || len(b) > 4<<20 {
		return nil, 0, errors.New("output read")
	}
	return b, st.Mode().Perm(), nil
}
func (v *Vault) Write(docs map[string]*Document, dry bool) ([]string, error) {
	if len(docs) != len(v.weeks) {
		return nil, errors.New("incomplete candidates")
	}
	if err := v.checkDirectory(); err != nil {
		return nil, err
	}
	var changed []string
	modes := map[string]os.FileMode{}
	for _, w := range v.weeks {
		doc := docs[w.Name]
		if doc == nil || doc.Week.Name != w.Name {
			return nil, errors.New("invalid candidate")
		}
		if _, err := ParseDocument(w, doc.Bytes()); err != nil {
			return nil, err
		}
		before, mode, err := v.read(w.Path())
		if err != nil {
			return nil, err
		}
		if !bytes.Equal(before, v.saved[w.Name]) {
			return nil, errors.New("output changed concurrently")
		}
		modes[w.Name] = mode
		if !bytes.Equal(before, doc.Bytes()) {
			changed = append(changed, w.Path())
		}
	}
	if dry || len(changed) == 0 {
		return changed, nil
	}
	if err := v.root.Mkdir("Autogenerated", 0700); err != nil && !os.IsExist(err) {
		return nil, errors.New("directory write")
	}
	if err := v.checkDirectory(); err != nil {
		return nil, err
	}
	dir, err := v.root.OpenRoot("Autogenerated")
	if err != nil {
		return nil, errors.New("directory access")
	}
	defer dir.Close()
	for _, path := range changed {
		name := strings.TrimPrefix(path, "Autogenerated/")
		week := strings.TrimSuffix(name, " Funnel.md")
		before, _, err := v.read(path)
		if err != nil || !bytes.Equal(before, v.saved[week]) {
			return nil, errors.New("output changed concurrently")
		}
		data := docs[week].Bytes()
		if err := replace(dir, name, data, modes[week]); err != nil {
			return nil, err
		}
		v.saved[week] = data
		v.Previous[week] = docs[week]
	}
	return changed, nil
}
func replace(root *os.Root, name string, data []byte, mode os.FileMode) error {
	temp := ".funnel-" + rand.Text() + ".tmp"
	file, err := root.OpenFile(temp, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0600)
	if err != nil {
		return errors.New("temporary write")
	}
	defer root.Remove(temp)
	if _, err = file.Write(data); err == nil {
		err = file.Chmod(mode)
	}
	if err == nil {
		err = file.Sync()
	}
	closeErr := file.Close()
	if err != nil || closeErr != nil {
		return errors.New("output write")
	}
	if err := root.Rename(temp, name); err != nil {
		return errors.New("atomic replace")
	}
	return nil
}
